Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,6 +26,27 @@ jobs:
       
       - name: Run API tests
         run: dotnet test Rest.sln --logger "trx"
+
+      - name: Verify allure-results directory
+        run: |
+         if [ -d "Rest/bin/Debug/net8.0/allure-results" ]; then
+         echo "✅ allure-results directory exists."
+         ls -la Rest/bin/Debug/net8.0/allure-results
+         else
+         echo "❌ allure-results directory does NOT exist."
+         exit 1
+
+      - name: Search for allure-results folder
+        run: |
+         echo "🔍 Searching for allure-results folder..."
+         FOUND_PATH=$(find . -type d -name "allure-results" | head -n 1)
+         if [ -n "$FOUND_PATH" ]; then
+         echo "✅ Found allure-results at: $FOUND_PATH"
+         ls -la "$FOUND_PATH"
+         else
+         echo "❌ allure-results folder not found."
+         exit 1
+         fi
         
       - name: Load Allure Test Report history
         uses: actions/checkout@v3
